spring:
  application:
    name: escape

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/escape}
    username: ${SPRING_DATASOURCE_USERNAME:escape}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: ${SPRING_SQL_INIT_MODE:never}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  # --- 소셜 로그인 (OAuth2) ---
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          kakao:
            provider: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - name
              - account_email

          naver:
            provider: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
              - profile

        provider:
          kakao:
            issuer-uri: https://kauth.kakao.com
          naver:
            issuer-uri: https://nid.naver.com

server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework

jwt:
  secret: ${JWT_SECRET}
  accessTokenExpirationMs: 1800000
  refreshTokenExpirationMs: 604800000

aws:
  region: ap-northeast-2
  s3:
    bucket: room-escape-dev
    public-base-url: https://room-escape-dev.s3.ap-northeast-2.amazonaws.com

app:
  frontend-base-url: ${FRONTEND_BASE_URL:http://localhost:3000}

auth:
  oauth:
    login-code-expiration-seconds: 60